/**
 * @module mbrApp/app-popup-builder
 * @author Boris <boris_here@mail.ru>
 * @description Popup builder
 */
defineM("popup-builder",function(h,a,l){function q(c,a){c.toggleClass("disabled",!a);c.attr("disabled",!a)}function p(c,b){if(0===c.indexOf("popup:")){var d;a:{for(var e=0;e<a.getResultJSON()[a.getCurrentPageName()].components.length;e++)if(-1!==c.indexOf(a.getResultJSON()[a.getCurrentPageName()].components[e]._popupId)){d=a.getResultJSON()[a.getCurrentPageName()].components[e];break a}for(d in a.getResultJSON())if(d!==a.getCurrentPageName())for(e=0;e<a.getResultJSON()[d].components.length;e++)if(-1!==
c.indexOf(a.getResultJSON()[d].components[e]._popupId)){d=h.extend(!0,{},a.getResultJSON()[d].components[e]);delete d._anchor;delete d._cid;d._id=a.getCoreUniqNum();a.getResultJSON()[a.getCurrentPageName()].components.push(d);a.render();break a}d=void 0}e=a.getComponent(b);if(e._global)for(var f in a.getResultJSON())if(f!==a.getCurrentPageName()){for(var g=!1,m=!1,k=0;k<a.getResultJSON()[f].components.length;k++)if(a.getResultJSON()[f].components[k]._name===e._name&&a.getResultJSON()[f].components[k]._id!==
e._id&&(g=!0),-1!==c.indexOf(a.getResultJSON()[f].components[k]._popupId)){m=!0;break}g&&!m&&(g=h.extend(!0,{},d),m=g._name.replace(/^pro\./i,""),m=m.replace(/\./g,"_")+"-",g._id=a.getCoreUniqNum(),g._cid=a.getUID(3,{timePrefix:!0}),g._anchor=m+a.getUniqCompName(),a.getResultJSON()[f].components.push(g))}}}var r,n;a.regExtension({name:"popup-builder",global:{getPopupList:function(){var c="",b=[],d;for(d in a.getResultJSON())for(var e=0;e<a.getResultJSON()[d].components.length;e++){var f=a.getResultJSON()[d].components[e];
if(("amp-popup"===f._name||"mbr-popup"===f._name)&&!b.includes(f._popupId)){b.push(f._popupId);var g=a.isAMP()?f._popupId.replace("amp-","mbr-"):f._popupId,c=c+('<option value="'+f._popupId+'">'+g+"</option>")}}return'<option value="" disabled="disabled" selected="selected"></option>'+c}},filters:{secondaryImgLinkUpdate:function(c,b){if(0===b.link.indexOf("popup:#")){var d=b.link.replace("popup:#","");a.isAMP()?c.attr("on","tap:"+d):c.attr({"data-toggle":"modal","data-bs-toggle":"modal","data-target":"#"+
d,"data-bs-target":"#"+d})}else c.removeAttr("on data-toggle data-bs-toggle data-target data-bs-target");return c},secondaryIconLinkUpdate:function(c,b){if(0===b.link.indexOf("popup:#")){var d=b.link.replace("popup:#","");a.isAMP()?c.attr("on","tap:"+d):c.attr({"data-toggle":"modal","data-bs-toggle":"modal","data-target":"#"+d,"data-bs-target":"#"+d})}else c.removeAttr("on data-toggle data-bs-toggle data-target data-bs-target");return c},popupUrl:function(a){return a="popup:#"+r.find(".note-mbr-popup").val()},
textLinkAnchors:function(c,b){if(0===b.url.indexOf("popup:#")){var d=b.url.replace("popup:#","");h.each(c,function(c,b){var g=h(b);a.isAMP()?g.attr("on","tap:"+d):g.attr({"data-toggle":"modal","data-bs-toggle":"modal","data-target":"#"+d,"data-bs-target":"#"+d});g.removeAttr("target")})}else b.ampCart||h.each(c,function(a,c){h(c).removeAttr("on data-toggle data-bs-toggle data-target data-bs-target")});return c},publishHTML:function(c){c=a.isAMP()?c.replace(/href="popup:#\S*"/g,""):c.replace(/href="popup:#\S*"/g,
'href="#"');if(n){var b=n;n="";c=c.replace("<html",'<html style="animation-delay: '+b+'s" class="overflow-hidden" [class]="lightboxOnLoad.visible ? \'overflow-visible\' : \'overflow-hidden\'"');c=c.replace("<body>",'<body>\n<amp-state id="lightboxOnLoad"><script type="application/json">{"visible": false}\x3c/script></amp-state>')}return c}},events:{successTextLinkDialog:function(a,b){a&&a.url&&p(a.url,b)},saveMediaImageDialog:function(a,b,d){b&&b.image&&b.image.link&&p(b.image.link,d)},showedLinkDialog:function(c){r=
c;var b='<li><a href="#popup" data-bs-toggle="tab" data-toggle="tab">'+l("Popup")+"</a></li>",d=c.find(".modal-body");d.find(".nav-tabs").append(b);d.find(".tab-content").append('<div class="tab-pane" id="popup"><div class="row form-group"><div class="col-sm-6"><select class="note-mbr-popup form-control"><option disabled="disabled">Nothing Selected</option></select></div></div></div>');d.find(".note-mbr-popup").html(a.getPopupList()).dropdown();var b=d.find(".note-mbr-custom-url"),e=b.val();0===e.indexOf("popup:#")&&
(b.val(""),d.find(".note-mbr-popup").val(e.replace("popup:#","")),d.find('.nav-tabs a[href="#popup"]').tab("show"));d.find(".note-mbr-popup").on("change",function(){q(c.find(".note-mbr-link-btn"),!0)});c.on("shown.bs.tab",'a[data-toggle="tab"][href="#popup"]',function(a){q(c.find(".note-mbr-link-btn"),d.find(".note-mbr-popup").val())})},getComponentsAnchorList:function(a){var b=h("<div>").html(a);b.find('[value*="amp-popup"], [value*="mbr-popup"]').remove();a=b[0].innerHTML;b.remove();return a},loadedComponent:function(c,
b,d,e){b=h(d).find("[data-app-component-id="+c._id+"] .app-component-content > .popup-builder");if(b.length)if(e){if(a.isAMP()){b.find(".popup-notification").remove();if(e=b.find(".mbr-popup").attr("data-timer-delay"))n=e,d=b.clone(),d.addClass("on-load-popup").removeClass("popup-builder").attr("id",c._popupId+"-onload").css("animation-delay",e+"s").find(".popup-close").attr({on:'tap:AMP.setState({"lightboxOnLoad": {"visible": true}}),'+c._popupId+"-onload.hide",role:"button",tabindex:"0"}),b.after(d);
b.find(".popup-close").attr({on:"tap:"+c._popupId+".close",role:"button",tabindex:"0"});b.find(">").wrapAll('<amp-lightbox id="'+c._popupId+'" class="cid-'+c._cid+'" layout="nodisplay" scrollable></amp-lightbox>');e=b.find("amp-lightbox")}else e=b.find(".mbr-popup"),e.addClass("cid-"+c._cid+" fade").attr({id:c._popupId,"aria-hidden":"true"}).find(".modal-dialog").addClass("modal-dialog-centered");b.after(e).remove()}else c._popupId||(c._popupId=a.isAMP()?c._anchor.replace("amp-","mbr-"):c._anchor),
c='<div style="position: absolute; width: 100%; height: 100%; margin-right: auto; margin-left: auto; padding-right: 15px; padding-left: 15px; text-align: center; color: #777777; font-size: 25px; overflow: hidden; z-index: 1;"><div class="row" style="height: 100%; align-items: center;"><div class="col"><div>'+l("Popup Builder")+'</div><div style="margin: 20px 0;"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="200" height="200" viewBox="0 0 32 32" fill="#777777" style="transform: rotate(-90deg);"><path d="M27.333 6.667c-0.451 0-0.667 0.33-0.667 0.667s0.216 0.667 0.667 0.667h2.667c0.381 0 0.667 0.286 0.667 0.667v21.333c0 0.381-0.286 0.667-0.667 0.667h-21.333c-0.381 0-0.667-0.286-0.667-0.667v-2.667c0.006-0.451-0.33-0.667-0.667-0.667s-0.673 0.216-0.667 0.667v2.667c0 1.096 0.904 2 2 2h21.333c1.096 0 2-0.904 2-2v-21.333c0-1.096-0.904-2-2-2zM2 0c-1.096 0-2 0.904-2 2v21.333c0 1.096 0.904 2 2 2h21.333c1.096 0 2-0.904 2-2v-21.333c0-1.096-0.904-2-2-2zM2 1.333h21.333c0.381 0 0.667 0.286 0.667 0.667v21.333c0 0.381-0.286 0.667-0.667 0.667h-21.333c-0.381 0-0.667-0.286-0.667-0.667v-21.333c0-0.381 0.286-0.667 0.667-0.667z"></path></svg></div><div>'+
l("The popup will appear on trigger only,<br>see block parameters")+'</div></div><div class="col"></div><div class="col"><div>'+l("Popup Builder")+'</div><div style="margin: 20px 0;"><svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="200" height="200" viewBox="0 0 32 32" fill="#777777" style="transform: rotate(-90deg);"><path d="M27.333 6.667c-0.451 0-0.667 0.33-0.667 0.667s0.216 0.667 0.667 0.667h2.667c0.381 0 0.667 0.286 0.667 0.667v21.333c0 0.381-0.286 0.667-0.667 0.667h-21.333c-0.381 0-0.667-0.286-0.667-0.667v-2.667c0.006-0.451-0.33-0.667-0.667-0.667s-0.673 0.216-0.667 0.667v2.667c0 1.096 0.904 2 2 2h21.333c1.096 0 2-0.904 2-2v-21.333c0-1.096-0.904-2-2-2zM2 0c-1.096 0-2 0.904-2 2v21.333c0 1.096 0.904 2 2 2h21.333c1.096 0 2-0.904 2-2v-21.333c0-1.096-0.904-2-2-2zM2 1.333h21.333c0.381 0 0.667 0.286 0.667 0.667v21.333c0 0.381-0.286 0.667-0.667 0.667h-21.333c-0.381 0-0.667-0.286-0.667-0.667v-21.333c0-0.381 0.286-0.667 0.667-0.667z"></path></svg></div><div>'+
l("The popup will appear on trigger only,<br>see block parameters")+"</div></div></div></div>",b.find(".mbr-popup").before(c)},load:function(){a.isAMP()&&a.registerAmpPlugin(["amp-onload-plugin"]);a.getCoreTemplate().on("click",'[data-toggle="modal"]',function(a){a.stopPropagation()})},updateGlobalComponents:function(c,b){var d=a.getComponent(c);if(d._popupId)for(var e in a.getResultJSON())if(e!==a.getCurrentPageName())for(var f=0;f<a.getResultJSON()[e].components.length;f++)a.getResultJSON()[e].components[f]._name===
d._name&&a.getResultJSON()[e].components[f]._id!==d._id&&a.getResultJSON()[e].components[f]._popupId===d._popupId&&b&&b(d,a.getResultJSON()[e].components[f])},savedMediaIconFontDialog:function(a,b,d){b&&b.iconFont&&b.iconFont.link&&p(b.iconFont.link,d)},showedComponentParams:function(c,b){if(b.find(".app-component-content > .popup-builder").length){var d=b.attr("data-app-component-id"),e=a.getComponent(d);a.$componentsParams.find(".dropdownjs").each(function(){var c=h(this).data("select");if(c.is("[name=popupOnPages]")){c.html(a.getPagesList());
var b=h(c.data("dropdownjs-ul")),d=h('<button class="btn btn-primary popup-select-all">Select All</button>');b.addClass("popup-dropdown").prepend(d);for(var k in a.getResultJSON())if(k===a.getCurrentPageName())b.find('[value="'+a.getCurrentPageName()+'"]').addClass("disabled").click();else for(var l=0;l<a.getResultJSON()[k].components.length;l++)if(a.getResultJSON()[k].components[l]._popupId===e._popupId){b.find('[value="'+k+'"]').click();break}c.on("change",function(){var c=h(this).val(),b;for(b in a.getResultJSON())if(b!==
a.getCurrentPageName()){for(var d=c.includes(b),f=!1,g=0;g<a.getResultJSON()[b].components.length;g++)if(a.getResultJSON()[b].components[g]._popupId===e._popupId){f=!0;d||a.removeComponent(a.getResultJSON()[b].components[g]._id,b);break}d&&!f&&(d=h.extend(!0,{},e),f=d._name.replace(/^pro\./i,""),f=f.replace(/\./g,"_")+"-",d._id=a.getCoreUniqNum(),d._cid=a.getUID(3,{timePrefix:!0}),d._anchor=f+a.getUniqCompName(),a.getResultJSON()[b].components.push(d))}});d.on("click",function(){b.find("li:not(.selected)").length?
b.find("li:not(.selected)").click():b.find('li:not([value="'+a.getCurrentPageName()+'"])').click()});return!1}});a.$componentsParams.find("> .cont > div").each(function(a,b){if(-1!==h(b).html().indexOf("[popup-id]"))return h(b).html(h(b).html().replace("[popup-id]","<code>"+e._popupId+"</code>")),!1})}}}})},["jQuery","mbrApp","TR()"]);
